"""Measurement datetime with timestamp

Revision ID: 2f5790feb9cf
Revises: d6328cd9f0d3
Create Date: 2018-05-03 19:02:22.053608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f5790feb9cf'
down_revision = 'd6328cd9f0d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_measurements_datetime'), 'measurements', ['datetime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_measurements_datetime'), table_name='measurements')
    # ### end Alembic commands ###
