"""Measurement model added

Revision ID: d6328cd9f0d3
Revises: f1bf9208a172
Create Date: 2018-05-03 16:08:38.919219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6328cd9f0d3'
down_revision = 'f1bf9208a172'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('height', sa.Numeric(scale=2), nullable=True),
    sa.Column('weight', sa.Numeric(scale=2), nullable=True),
    sa.Column('imc', sa.Numeric(scale=2), nullable=True),
    sa.Column('fat_percentage', sa.Numeric(scale=2), nullable=True),
    sa.Column('muscle_mass', sa.Numeric(scale=2), nullable=True),
    sa.Column('water_percentage', sa.Numeric(scale=2), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('measurements')
    # ### end Alembic commands ###
