"""Deleted appointments

Revision ID: f1bf9208a172
Revises: c1c1159d7e2e
Create Date: 2018-04-24 13:03:57.341641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1bf9208a172'
down_revision = 'c1c1159d7e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('nutritionist_id', sa.INTEGER(), nullable=True),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('isConfirmed', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('"isConfirmed" IN (0, 1)'),
    sa.ForeignKeyConstraint(['nutritionist_id'], ['nutritionists.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
